name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install dependencies
        run: brew install valkey
      - name: Build using Makefile
        run: USE_SSL=1 make
      - name: Run tests 1
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
      - name: Run tests 2
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
      - name: Run tests 3
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
      - name: Run tests 4
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
      - name: Run tests 5
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
      - name: Run tests 6
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
      - name: Run tests 7
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
      - name: Run tests 8
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
      - name: Run tests 9
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
      - name: Run tests 10
        working-directory: tests
        env:
          TEST_SSL: 1
        run: ./test.sh
