name: Spellcheck
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Run spellcheck
        uses: rojopolis/spellcheck-github-actions@d5aba66a94528674ea744124f9ebcfd55e945836 # 0.43.1
        with:
          config_path: .github/spellcheck-settings.yml
          task_name: Markdown
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install typos
        uses: taiki-e/install-action@437c908c7e5ee18b63a261286cbe5147219f8a39 # v2.44.44
        with:
          tool: typos
      - name: Run typos
        run: typos --config=.github/typos.toml
